### PR TITLE
Add sphinx documentation

### PR DESCRIPTION
**Pull request by raphapassini**
Hello dear reviewer,

I basically did three things:
- Add the sphinx to the requirements-development.txt
- Create a basic documentation, based on the Readme, with few improvements i've made.
- Move some basic project information (intro and archtecture) to the **init**.py of the rows module

I think the Sphinx doc can also be used as a website, and maybe can be hosted at github pages.

[]'s
I hope this will be usefull! :)

### CODE REVIEW

**Comment by turicas** [comment]
@raphapassini, thanks! :) I'm going to have a look in all changes during this week.

**Comment by raphapassini** [comment]
Hi @turicas, it's been a time since i've opened this request, any feedbacks? Thx.

**Comment by turicas** [comment]
@raphapassini, sorry for the delay! Let's go:

- The commits 45d7636c9c8cd0fc1c9e974b61ee42aea99883d3 and 1ca8cd9baf71ad8fa96a8d76bf33d68ef51f025d are ok;
- The commit c424ace320e43afbc36c12289e1ac133f100159e put a lot of static/binary files into the main branch and it's not the desired behaviour. I can create another branch (based on yours) and take only the files on `rows-doc/source`, since the source of the docs will be inside the main branch, but the "compiled" docs/site needs to sit on `gh-pages` branch (see more details on [GitHub Pages docs](http://pages.github.com)).

I think the best approach would be:

- Create a brand-new branch off of the current `develop`
- Cherry-pick the commits 45d7636c9c8cd0fc1c9e974b61ee42aea99883d3 and 1ca8cd9baf71ad8fa96a8d76bf33d68ef51f025d
- Follow the instructions on [continuous-docs](https://github.com/icgood/continuous-docs/)
- Checkout to commit c424ace320e43afbc36c12289e1ac133f100159e and copy to another folder only the doc sources
- Checkout again to the new branch and put the sources in there and commit

Can you please do these changes? We can do it together at PythonBrasil if you prefer! :+1:

Thanks again for your collaboration!

**Comment by turicas** [comment]
This PR is related to #43.

**Comment by turicas** [comment]
Closing this issue since Sphinx was added [on another PR](https://github.com/turicas/rows/pull/205).

**Pull request closed without merging**
