### PR TITLE
fix issue #181 with slug creation

### PR DESCRIPTION
**Pull request by humrochagf**

### CODE REVIEW

**Comment by turicas** [comment]
Thanks for your PR. Could you please address the following changes:

- Create a unit test for this feature
- Replace `type`  with other name (it's a Python function)
- Add your name to `AUTHORS`

?

**Comment by humrochagf** [comment]
@turicas sorry man missed the message, found today looking back to my PR`s history.

I've updated everything, and added some small cleanups.

**Comment by humrochagf** [comment]
And one question:
Since this fix that question should I remove these comment lines?
```
# TODO: should use slug on each field name automatically or inside each
#       plugin?
```

**Comment by turicas** [comment]
I've rebased the branch, changed little things related to imports (the changes you've made won't work on Python2) and merged in df91f5445f2add4c27664abeaacabb17de135b37.
Thanks! :)

**Pull request closed without merging**
